name: Just Build
on:
  workflow_dispatch:
    inputs:
      do_push:
        type: boolean
        description: do push
        required: true
        default: false
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
env:
  BUILD_ENV: 'github'
jobs:
  nginx:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    env:
      PLATFORMS: linux/amd64,linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
        with:
          version: latest
          platforms: ${{ env.PLATFORMS }}
      - name: Login to ACR
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build-nginx-image
        run: |
          TIME=$(date +"%Y%m%d%H%M%S")
          TAG=v1.12.3.${TIME} # the controller image tag
          BASE_IMAGE=registry.cn-hangzhou.aliyuncs.com/cong-ingress-nginx/nginx:v2.2.0.20250826072222
          REGISTRY=registry.cn-hangzhou.aliyuncs.com/cong-ingress-nginx
          make VERBOSE=1 PLATFORMS="amd64 arm64" BUILDX_PLATFORMS="linux/amd64,linux/arm64" BASE_IMAGE=$BASE_IMAGE REGISTRY=$REGISTRY TAG=$TAG release
